### ISSUE TITLE
Segmentation fault on large input file

### ISSUE THREAD

**Issue by gauravaror** [xapian/xapian-evaluation#4]

**Comment by ojwb** [comment]
I can reproduce the segfault.

It also looks like only the first up to 30000000 bytes of the input file (after decompression) are read, which ought to be fixed.

**Comment by ojwb** [comment]
Poking with gdb the problem seems to be that `curpos` ends up being `-1` in `readline()`.  I'm not seeing how that happens, but this code is needlessly very inefficient (it copies the input line by line when we can just scan the buffer it's already in) so I fixed that in 0bb5f9b51f273e2c4d9976fc8c28e0a9c6ce3dd3 and that's made the segfault go away.

So I think we can assume this is fixed.  If it recurs please reopen and give details on reproducing.
